"use strict";
const state={lab:LABS.saucedemo,view:"accueil",stories:[],selectedStory:0,traceCache:{},pipelineCache:{}};
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const labels={success:"Succès",failure:"Échec",cancelled:"Annulée",skipped:"Ignorée",timed_out:"Délai dépassé",action_required:"Action requise",neutral:"Neutre",stale:"Obsolète",startup_failure:"Échec au démarrage",in_progress:"En cours",queued:"En attente",unknown:"Autre"};
const colors={success:"#22c55e",failure:"#ef4444",fixme:"#f59e0b",cancelled:"#f59e0b",skipped:"#94a3b8",timed_out:"#fb7185",action_required:"#c084fc",neutral:"#60a5fa",unknown:"#29415e"};
function esc(v){const d=document.createElement("div");d.textContent=String(v??"");return d.innerHTML}
function sync(message,active=false){$("#sync-status").innerHTML=`<i${active?' class="syncing"':''}></i> ${message}`}
function metricCards(items){return items.map(x=>`<article class="metric-card"><span>${x.label.toUpperCase()}</span><strong>${x.value}</strong><small>${x.note||"Périmètre documenté"}</small></article>`).join("")}
function closeMenu(){$("#sidebar").classList.remove("open");$("#menu-button").setAttribute("aria-expanded","false")}
function switchView(view){state.view=view;document.body.classList.toggle("welcome-mode",view==="accueil");$$('[data-view-panel]').forEach(x=>x.classList.toggle("active",x.dataset.viewPanel===view));$$('[data-view]').forEach(x=>x.classList.toggle("active",x.dataset.view===view));$("#view-kicker").textContent=VIEW_META[view][0];$("#view-title").textContent=VIEW_META[view][1];history.replaceState(null,"",`#vue-${view}`);if(view==="pipeline")loadPipeline();closeMenu()}
function setLab(id){state.lab=LABS[id]||LABS.saucedemo;state.selectedStory=0;const repo=`https://github.com/${state.lab.repo}`;$("#project-select").value=state.lab.id;$("#mobile-lab").textContent=state.lab.code;$("#repo-link").href=repo;$("#project-repo-link").href=repo;$("#app-link").href=state.lab.app;$("#project-code").textContent=state.lab.code;$("#project-type").textContent=state.lab.type;$("#project-name").textContent=state.lab.name;$("#project-summary").textContent=state.lab.summary;$("#project-metrics").innerHTML=metricCards(state.lab.metrics);$("#portal-project-name").textContent=state.lab.name;$("#qa-portal-link").href=state.lab.portal;renderResults();loadTrace();if(state.view==="pipeline")loadPipeline()}
function renderResults(){const r=state.lab.results;$("#result-metrics").innerHTML=metricCards([{value:r.total,label:"Tests Playwright",note:"Suite automatisée documentée"},{value:r.passed,label:"Réussis",note:"Dernier résultat communiqué"},{value:r.fixme,label:"Fixme / skipped",note:"Dette connue et visible"},{value:r.defects,label:"Défauts documentés",note:"Écarts tracés dans le projet"}]);const seg=[{label:"Réussis",value:r.passed,color:colors.success},{label:"Fixme / skipped",value:r.fixme,color:colors.fixme},{label:"Échecs inattendus",value:r.failed,color:colors.failure}].filter(x=>x.value);let cursor=0;$("#results-donut").style.background=`conic-gradient(${seg.map(x=>{const a=cursor;cursor+=x.value/r.total*100;return`${x.color} ${a}% ${cursor}%`}).join(",")})`;$("#results-total").textContent=r.total;$("#results-legend").innerHTML=seg.map(x=>`<li><i style="background:${x.color}"></i>${x.label} · ${x.value}</li>`).join("");const max=Math.max(...r.levels.map(x=>x.value));$("#levels-chart").innerHTML=r.levels.map(x=>`<div class="bar-row"><span>${x.name}</span><div><i style="width:${x.value/max*100}%"></i></div><b>${x.value}</b></div>`).join("");$("#result-insights").innerHTML=r.insights.map(x=>`<div><strong>${x.title}</strong><p>${x.text}</p></div>`).join("")}
async function fetchText(path){const result=await githubDataCache.getText(`https://raw.githubusercontent.com/${state.lab.repo}/main/${path}`);if(result.source!=="live")state.traceFallback=result;return result.data}
function parseSauce([storiesText,criteriaText,matrixText]){const map={"01":"AUTH","02":"CAT","03":"SORT","04":"CART","05":"CHK","06":"SESSION"};const stories=[...storiesText.matchAll(/^## (US-\d+) — (.+)\n\n([\s\S]*?)(?=\n## |$)/gm)].map(m=>({id:m[1],title:m[2],description:m[3].replace(/\n/g," ").trim(),criteria:[]}));const criteria=[...criteriaText.matchAll(/^### (AC-[A-Z]+-\d+) — (.+)\n([\s\S]*?)(?=\n### |\n## |$)/gm)].map(m=>({id:m[1],title:m[2],description:(m[3].match(/\*\*Description :\*\*\s*([^\n]+)/)||[])[1]||"Comportement observable documenté.",tests:[]}));matrixText.split("\n").filter(x=>/^\| [^|-]/.test(x)&&/TC-/.test(x)).forEach(line=>{const c=line.split("|").slice(1,-1).map(x=>x.trim().replace(/`/g,""));const criterion=criteria.find(x=>x.id===c[2]);if(criterion)criterion.tests.push({id:c[3],title:`${c[0]} · ${c[4]}`,level:"UI",priority:c[5],detail:c[6]})});stories.forEach(s=>{const key=map[s.id.slice(-2)];s.criteria=criteria.filter(c=>c.id.startsWith(`AC-${key}-`))});return stories}
function parsePlan(text,path){const head=(text.match(/^# Plan de test — ([^\n]+)/m)||[])[1]||path;const us=(head.match(/US-[A-Z-]+-\d+/)||[])[0]||"US";const title=head.replace(`${us} — `,"").replace(us,"").trim()||us.replace(/^US-|-[0-9]+$/g,"").replaceAll("-"," ");const description=(text.match(/## (?:Objet et stratégie|Stratégie de couverture)\n\n([^\n]+)/)||[])[1]||"Plan de test structuré selon les risques et la responsabilité vérifiée.";const tests=[...text.matchAll(/^### (TC-[A-Z-]+-\d+) — (.+)\n([\s\S]*?)(?=\n### |\n## |$)/gm)].map(m=>{const block=m[3];return{id:m[1],title:m[2],acs:[...new Set([...block.matchAll(/`(AC-\d+)`/g)].map(x=>x[1]))],level:(block.match(/\*\*(?:Niveau|Niveau principal)\s*:?\*\*\s*:?\s*`?([A-Z_]+)/)||[])[1]||"UI_MOCKED",priority:((block.match(/\*\*Priorité\s*:?\*\*\s*:?\s*([^\n]+)/)||[])[1]||"Définie").replaceAll("`",""),detail:((block.match(/\*\*Question principale\s*:?\*\*\s*:?\s*([^\n]+)/)||[])[1]||m[2]).replaceAll("`","")}});const ids=[...new Set(tests.flatMap(x=>x.acs))].sort((a,b)=>Number(a.slice(3))-Number(b.slice(3)));return{id:us,title,description,criteria:ids.map(id=>({id,title:`Critère ${id}`,description:"Critère d'acceptation documenté, relié aux scénarios ci-dessous.",tests:tests.filter(t=>t.acs.includes(id))}))}}
async function loadTrace(){const key=state.lab.id;if(state.traceCache[key]){state.stories=state.traceCache[key];renderTrace();return}sync("Synchronisation GitHub…",true);$("#feature-list").innerHTML="";$("#trace-detail").innerHTML='<div class="empty-state"><i class="fa-solid fa-spinner fa-spin"></i><p>Lecture des plans de test…</p></div>';try{const texts=await Promise.all(state.lab.trace.files.map(fetchText));state.stories=state.lab.trace.kind==="sauce"?parseSauce(texts):texts.map((t,i)=>parsePlan(t,state.lab.trace.files[i]));state.traceCache[key]=state.stories;renderTrace();sync("Traçabilité synchronisée")}catch(e){state.stories=[];$("#trace-detail").innerHTML='<div class="empty-state"><i class="fa-solid fa-triangle-exclamation"></i><p>La traçabilité GitHub est temporairement indisponible.</p></div>';$("#trace-count").textContent="Indisponible";sync("Synchronisation impossible")}}
function renderTrace(filter=""){const q=filter.trim().toLowerCase(),matches=state.stories.map((story,index)=>({story,index})).filter(x=>!q||JSON.stringify(x.story).toLowerCase().includes(q));$("#feature-list").innerHTML=matches.map(({story,index})=>`<button class="feature-item ${index===state.selectedStory?'active':''}" data-story="${index}" role="listitem"><b>${String(index+1).padStart(2,"0")}</b><span><strong>${esc(story.title)}</strong><small>${esc(story.id)}</small></span><span>${story.criteria.length} AC</span></button>`).join("")||'<div class="empty-state"><p>Aucun résultat.</p></div>';const uniqueTests=new Set(state.stories.flatMap(s=>s.criteria.flatMap(c=>c.tests.map(t=>t.id))));$("#trace-count").textContent=`${state.stories.length} US · ${uniqueTests.size} cas`;$$("[data-story]").forEach(b=>b.addEventListener("click",()=>{state.selectedStory=Number(b.dataset.story);renderTrace(filter)}));const story=state.stories[state.selectedStory]||matches[0]?.story;if(!story){$("#trace-detail").innerHTML='<div class="empty-state"><p>Aucune donnée correspondante.</p></div>';return}$("#trace-detail").innerHTML=`<div class="story-head"><span>${esc(story.id)}</span><h3>${esc(story.title)}</h3><p>${esc(story.description)}</p></div>${story.criteria.map((c,i)=>`<details class="criterion" ${i===0?'open':''}><summary><b>${esc(c.id)}</b><strong>${esc(c.title)}</strong><span>${c.tests.length} cas</span></summary><div class="criterion-body"><p>${esc(c.description)}</p>${c.tests.map(t=>`<article class="test-case"><header><b>${esc(t.id)} · ${esc(t.title)}</b><span>${esc(t.level)}</span></header><p>${esc(t.detail)} · Priorité ${esc(t.priority)}</p></article>`).join("")||'<p>Aucun cas directement associé.</p>'}</div></details>`).join("")}`}
function duration(run){return run.run_started_at&&run.updated_at?Math.max(0,new Date(run.updated_at)-new Date(run.run_started_at)):null}
function formatDuration(ms){if(ms===null)return"—";const s=Math.round(ms/1000);return s<60?`${s} s`:`${Math.floor(s/60)} min ${s%60} s`}
function formatDate(v){return new Intl.DateTimeFormat("fr-FR",{dateStyle:"medium",timeStyle:"short"}).format(new Date(v))}
function conclusion(run){return run.status!=="completed"?run.status:(run.conclusion||"unknown")}
function pipelineState(message,type="loading"){$("#pipeline-state").className=`api-state ${type}`;const icon=type==="ready"?"fa-circle-check":type==="cached"?"fa-clock-rotate-left":"fa-triangle-exclamation";$("#pipeline-state").innerHTML=type==="loading"?`<span class="loader"></span> ${message}`:`<i class="fa-solid ${icon}"></i> ${message}`}
async function loadPipeline(){const key=state.lab.id;if(state.pipelineCache[key]){renderPipeline(state.pipelineCache[key].data);return pipelineState(state.pipelineCache[key].message,state.pipelineCache[key].type)}pipelineState("Connexion à l'API GitHub…");try{const base=`https://api.github.com/repos/${state.lab.repo}/actions`,[runsResult,workflowsResult]=await Promise.all([githubDataCache.getJSON(`${base}/runs?per_page=50`),githubDataCache.getJSON(`${base}/workflows?per_page=100`)]);const data={runs:runsResult.data.workflow_runs||[],workflows:workflowsResult.data.workflows||[]},fallback=[runsResult,workflowsResult].filter(x=>x.source!=="live").sort((a,b)=>new Date(b.updatedAt||0)-new Date(a.updatedAt||0))[0],type=fallback?"cached":"ready",message=fallback?githubDataCache.sourceLabel(fallback,"API indisponible · dernières données conservées"):`Données actualisées · ${formatDate(new Date())}`;state.pipelineCache[key]={data,message,type};renderPipeline(data);pipelineState(message,type)}catch(e){renderPipeline({runs:[],workflows:[]});pipelineState("Aucune donnée GitHub ou sauvegarde disponible.","error")}}
function renderPipeline({runs,workflows}){
  const completed=runs.filter(x=>x.status==="completed"),success=completed.filter(x=>x.conclusion==="success"),stability=completed.length?Math.round(success.length/completed.length*100):0,durations=completed.map(duration).filter(x=>x!==null),avg=durations.length?durations.reduce((a,b)=>a+b,0)/durations.length:null;
  $("#stability").textContent=completed.length?`${stability} %`:"—";$("#stability-bar").style.width=`${stability}%`;$("#stability-caption").textContent=`${success.length} succès sur ${completed.length} exécutions terminées`;$("#runs-total").textContent=runs.length;$("#runs-success").textContent=success.length;$("#runs-duration").textContent=formatDuration(avg);$("#actions-link").href=`https://github.com/${state.lab.repo}/actions`;
  const recent=runs.slice(0,30).reverse();$("#timeline-chart").innerHTML=recent.length?recent.map(x=>`<span class="timeline-bar ${conclusion(x)==="success"?'success':''}" style="height:${x.status==="completed"?75:45}%" title="${esc(x.name)} · ${labels[conclusion(x)]||labels.unknown}"></span>`).join(""):'<p>Aucune exécution disponible.</p>';
  const counts=completed.reduce((a,x)=>(a[x.conclusion||"unknown"]=(a[x.conclusion||"unknown"]||0)+1,a),{}),entries=Object.entries(counts).sort((a,b)=>b[1]-a[1]);let cursor=0;$("#pipeline-donut").style.background=entries.length?`conic-gradient(${entries.map(([k,n])=>{const start=cursor;cursor+=n/completed.length*100;return`${colors[k]||colors.unknown} ${start}% ${cursor}%`}).join(",")})`:"#29415e";$("#pipeline-donut-total").textContent=completed.length;$("#pipeline-legend").innerHTML=entries.map(([k,n])=>`<li><i style="background:${colors[k]||colors.unknown}"></i>${labels[k]||labels.unknown} · ${n}</li>`).join("")||"<li>Aucune conclusion</li>";
  $("#workflows-table").innerHTML=workflows.length?workflows.map(w=>`<tr><td><a href="${w.html_url}" target="_blank" rel="noopener noreferrer">${esc(w.name)}</a></td><td>${w.state==="active"?"Actif":"Désactivé"}</td><td><code>${esc(w.path)}</code></td><td>${formatDate(w.updated_at)}</td></tr>`).join(""):'<tr><td colspan="4">Aucun workflow public trouvé.</td></tr>';
  $("#runs-table").innerHTML=runs.length?runs.slice(0,15).map(run=>{const value=conclusion(run),cls=value==="success"?"success":value==="failure"?"failure":"";return`<tr><td><a href="${run.html_url}" target="_blank" rel="noopener noreferrer">#${run.run_number}</a></td><td>${esc(run.name)}</td><td>${esc(run.head_branch||"—")}</td><td><span class="run-status ${cls}"><i></i>${labels[value]||labels.unknown}</span></td><td>${formatDuration(duration(run))}</td><td>${formatDate(run.created_at)}</td></tr>`}).join(""):'<tr><td colspan="6">Aucune exécution publique trouvée.</td></tr>';
}
document.addEventListener("DOMContentLoaded",()=>{$("#year").textContent=new Date().getFullYear();$$('[data-view]').forEach(b=>b.addEventListener("click",()=>switchView(b.dataset.view)));$("#project-select").addEventListener("change",e=>setLab(e.target.value));$("#trace-search").addEventListener("input",e=>renderTrace(e.target.value));$("#menu-button").addEventListener("click",()=>{const open=$("#sidebar").classList.toggle("open");$("#menu-button").setAttribute("aria-expanded",String(open))});setLab("saucedemo");const view=location.hash.replace("#vue-","");switchView(VIEW_META[view]?view:"accueil")});
