"""Rebuild LAB_03's source-based views from the upstream BILAN-V1.1.1.md copy."""
import json
import re
from pathlib import Path

root = Path(__file__).resolve().parents[1]
source = (root / 'content/BILAN-V1.1.1.md').read_text()
sections = {}
for match in re.finditer(r'^## (.+)$', source, re.M):
    next_match = re.search(r'^## ', source[match.end():], re.M)
    end = match.end() + next_match.start() if next_match else len(source)
    sections[match.group(1)] = source[match.end():end].strip()

def plain(value):
    value = re.sub(r'\[([^]]+)\]\([^)]*\)', r'\1', value)
    return re.sub(r'[`*]', '', value).strip()

lessons = []
for match in re.finditer(r'^### (.+)$', sections['Enseignements vulgarisés'], re.M):
    rest = sections['Enseignements vulgarisés'][match.end():]
    next_match = re.search(r'^### ', rest, re.M)
    body = rest[:next_match.start()] if next_match else rest
    lessons.append([plain(match.group(1)), plain(body.strip().split('\n\n')[0])])
assert len(lessons) == 9
names = ['Situation de départ', 'Problèmes rencontrés', 'Solutions apportées', 'Résultats v1.1.1', 'Ce qui reste à corriger dans le produit', 'Enseignements vulgarisés', 'Conclusion']
tabs = [{'id': f'v111-{i}', 'label': name, 'heading': name, 'blocks': [{'t':'md','md':sections[name]}]} for i,name in enumerate(names)]
bilan = {'file':'BILAN-V1.1.1.md','title':'Bilan QA de la version v1.1.1',
         'lead':{'intro':'Le texte ci-dessous reprend BILAN-V1.1.1.md, document de la première campagne v1.1.1. Depuis sa rédaction, le README du dépôt annonce 18 User Stories, 172/181 critères vérifiés, 143 cas planifiés et 136 tests automatisés. Les tableaux de résultats du portfolio suivent ce nouvel état ; les chiffres historiques du bilan sont conservés comme contexte.',
                 'heading':'Résumé', 'md':sections['Résumé']}, 'tabs':tabs}
out = '// Generated by scripts/build-v111-content.py from content/BILAN-V1.1.1.md.\n'
out += 'BILAN[V111_ID] = ' + json.dumps(bilan,ensure_ascii=False,indent=2) + ';\n'
out += 'RISK_LEARNING[V111_ID].lessons = ' + json.dumps(lessons,ensure_ascii=False,indent=2) + ';\n'
(root/'js/french-v111-content.js').write_text(out)
print(f'{len(tabs)} bilan tabs and {len(lessons)} source lessons')
